### ISSUE TITLE
Ghosts get out of sync, sometimes causing crashes

### ISSUE THREAD

**Issue by kb173** [lizrad/recursio#108]
Examples:

- server says ghost with ID 2 died, but client doesn't know about this ghost
- ghost stays stationary at capture point on the client, leading to 4 player characters being displayed
- dead ghost keeps moving and seems to have an active collider

**Comment by AmonShokhinAhmed** [comment]
This is still kinda happening. First point should be hotfixed with c6fd582. It might be connected to there being three existant ghosts on the server after the third round (although one should always be deactivated).

The other two points have not been observed anymore. But ghost are sometimes not visible on clients. No consistent way to reproduce has been found yet.

**Comment by AmonShokhinAhmed** [comment]
There is also a race condition where ghosts are slightly out of sync because of code execution order, causing misses where ghost have hit as active players.

We also once observed ghosts being completely out of sync. This was not reproduceable.

**Comment by AmonShokhinAhmed** [comment]
Seems to work well after 951d229. 🥳
