### ISSUE TITLE
Fix runtime errors for CapturePoints progress

### ISSUE THREAD

**Issue by incredibleLeitman** [lizrad/recursio#121]
dunno excatly how to and also seem to dont cause actual problems 🤷‍♂️ 
![image](https://user-images.githubusercontent.com/24638443/142612802-d8a39d98-ef66-4b51-a5e1-c1c64683af50.png)
Maybe this can be prevented by setting the ViewportTexture for the Sprite3D after adding the capture point to the scene

also check if it is possible to re-enable ascii shader for CapturePoints meshes

**Comment by AmonShokhinAhmed** [comment]
Fixed when #173 is merged.
