### ISSUE TITLE
Make timeline paths during selection clearer

### ISSUE THREAD

**Issue by kb173** [lizrad/recursio#150]
- maybe make them thinner
- consider only displaying the currently selected timeline or strongly emphasizing it

**Comment by DavidPgl** [comment]
am Anfang 100% opacity und dann zum Ende ausfaden (evtl. nicht kompletten Path)

**Comment by AmonShokhinAhmed** [comment]
Also make the distance between displayed paths shorter maybe (from 30 to 15)
