### ISSUE TITLE
Camera during prep phase does not zoom out sometimes

### ISSUE THREAD

**Issue by AmonShokhinAhmed** [lizrad/recursio#171]
During the prep phase the camera normally shows an overview of the  whole level, but when I played it online it stayed at the game zoom level on both clients during the fourth round. Then it happend again in the sixth round.

**Comment by DavidPgl** [comment]
Could be a connected to capturing point and loosing capture point as the camera is moved there as well (maybe when the round is finished while the capture point is being captured or when you loose it when the round ends?)

**Comment by AmonShokhinAhmed** [comment]
Fixed when #173 is merged.
