### ISSUE TITLE
Ghosts that shouldn't yet exist show up on the client sometimes

### ISSUE THREAD

**Issue by kb173** [lizrad/recursio#174]
Example scenario where it occured (but can't reliably be reproduced): Start with a hitscan timeline, then play the other hitscan timeline -> the wall ghost shows up

It seems like that ghost might have some movement data, at least we saw it do something, it didn't just stand there.

Because it's possible to glitch through it, we assume that it only exists on the client.

**Comment by DavidPgl** [comment]
Could not reproduce with current project state

**Comment by kb173** [comment]
Hotfixed in the above commit; we should fix it properly in the commented-out code, but this works for now
