### ISSUE TITLE
Wrong ghost path highlighted

### ISSUE THREAD

**Issue by DavidPgl** [lizrad/recursio#204]
Could not reproduce it reliable but most of the times it happened when selecting third ghost in round 1 and first in round 2 and then viewing them in round 3

Possibilities:
- Internet and thereby ghost switching (as I tested it on the train)
- Ghost somehow gets the same path from last played ghost as both paths are visible (and clipping) when selecting the third ghost

**Comment by kb173** [comment]
Seems to be the same as #174, closing in favor of that one
