### ISSUE TITLE
Also allow joystick for UI navigation

### ISSUE THREAD

**Issue by AmonShokhinAhmed** [lizrad/recursio#228]

**Comment by incredibleLeitman** [comment]
I tried if just adding device joy axis for ui_up/down in project input settings works,
but this seems to trigger focus changes multiple times for each input.

If there is no "trick" handling this with internal Godot settings this have to be implemented manually and I think the effort involved would be far greater than the benefit.

**Comment by AmonShokhinAhmed** [comment]
![image](https://user-images.githubusercontent.com/32668336/150499766-405f0d3a-2a8a-49d9-a3c1-4ba147bc7af9.png)
This works for me though? (Only tried it in the main menu screen)

**Comment by incredibleLeitman** [comment]
yeah, the select works in principle, but with my XBox controller, moving the stick up or down just a little bit instantly skips 3 buttons xD
