### ISSUE TITLE
Opening menu during prep phase in tutorial disables all controls in tutorial 1

### ISSUE THREAD

**Issue by AmonShokhinAhmed** [lizrad/recursio#231]

**Comment by incredibleLeitman** [comment]
`func toggle_player_input_pause(value: bool) -> void:` in CharacterManager stores current player movement_ and swapping_toggle values on entering pause mode,
but does not forward changes for the actual player values.

Way more "dangerous" effect of this: if the player pauses while movement is enabled and resumes in a phase where input should be disabled, he gets the previously stored permissions which allows to run around
