### ISSUE TITLE
Ghost in Tutorial 2 is still there causing weird beahviour

### ISSUE THREAD

**Issue by DavidPgl** [lizrad/recursio#250]
- Warning circle is triggered (confused some players)
- "Place here" arrow moves back to the enemy spawn point with the disabled ghost

**Comment by AmonShokhinAhmed** [comment]
First point is kinda tricky to fix because with the way things are setup I can't just not have an enemy player (so it is just made invisible).
I couldn't reproduce the second point, how exactly did you do that?

**Comment by DavidPgl** [comment]
Same here, guess it was a one time thing
