### ISSUE TITLE
Create some kind of config file for important settings

### ISSUE THREAD

**Issue by AmonShokhinAhmed** [lizrad/recursio#43]
Because right now we have to define lots of stuff on the client as well as on the server.  Would be very helpful if both could just read from the same file.

**Comment by kb173** [comment]
done:

- the shared repo https://github.com/lizrad/recursio-shared was added as a submodule in the client and in the server.
- GitHub Actions keep the client and server at the latest version of this shared repo by reacting to notifications for new commits.
- a file for all constants `constants.ini`, an access script `Constants.gd`, as well as the logger were added to this shared repo.

so: whatever code or values that can or must be shared between server and client should go into https://github.com/lizrad/recursio-shared. commits to that repo are automatically applied in the server and client, but not necessarily in your local copies, so __don't forget to pull in your local client and/or server repo after making changes to the shared code__
