### ISSUE TITLE
Slightly refactor gameplay recording in Player

### ISSUE THREAD

**Issue by kb173** [lizrad/recursio#84]
The way the `gameplay_record["W"]` is handled could be improved, and we might generally want to do the action saving more like how we transmit play action data over the network (with pre-selected Actions, and only Triggers being saved).

**Comment by kb173** [comment]
@DavidPgl is this fixed on the branch?

**Comment by DavidPgl** [comment]
Yes 🙏

**Comment by kb173** [comment]
neat
